spring.application.name=manutencao
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/manutencao
spring.datasource.username=manutencao
spring.datasource.password=manutencao123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true